### PR TITLE
Remove cookies header from rack_response that was added in v6 release

### PR DESCRIPTION
**Pull request by jeremiahlukus**
Fixes:  https://github.com/rails-lambda/lamby/issues/78 

I also added tests to prevent this from happening again.

### CODE REVIEW

**Comment by jeremiahlukus** [comment]
@metaskills  This fixes and issue i caused in v6 by adding the cookies header which does not conform to the required Lambda proxy integration.

**Comment by jeremiahlukus** [comment]
@metaskills  mind looking at this when you get a few and releasing?

**Comment by jeremiahlukus** [comment]
Added release stage 

https://github.com/rails-lambda/lamby/issues/183

It depends on 

`secrets.RUBYGEMS_API_KEY` So you need to add that.

**Comment by metaskills** [comment]
Hmm, I do not mind. Would that help if I have 2FA setup?

**Comment by jeremiahlukus** [comment]
I dont think this matters to use an api key, but its always a good idea to have 2fa setup ha

**Comment by metaskills** [comment]
I was asking Perplexity how to go about things and it brought up the trusted publishing method. Thoughts?

- https://guides.rubygems.org/trusted-publishing/releasing-gems/
- https://github.com/rubygems/release-gem?tab=readme-ov-file

**Comment by metaskills** [comment]
I just setup a trusted publisher for this repo to the lamby gem. I chose the same filename for the action too. Lemme know how this goes. The rubygems action looks slick.

Screenshot 2024-08-29 at 6 25 54 PM

**Comment by jeremiahlukus** [comment]
O sweet I didn’t know this was an option this is a much better solution than using a LTK. I’ll refactor for this.

**Comment by metaskills** [comment]
Wow, did that just work? So cool!

https://rubygems.org/gems/lamby/versions/6.0.1

Screenshot 2024-08-30 at 9 21 10 AM

**Comment by jeremiahlukus** [comment]
Yep, definitely going to use this for other projects. So much better ha

**Pull request merged**
